/* ==================================================================
   GAMES — 20 token sets driving 3 shared motion archetypes.
   Adding a 21st game is a data entry, not an animation job.
   Every fact carries a real curriculum idea: counting, shape,
   measurement, fractions, states of matter, forces.
   ================================================================== */
const GAMES = [
 {id:'cricket',en:'Cricket',hi:'क्रिकेट',ic:'🏏',type:'launch',actor:'🏏',proj:'🔴',accent:'#3FBB78',
  fact:{en:'A cricket pitch is 22 yards long — about 20 metres, or 12 kids lying head to toe!',hi:'क्रिकेट की पिच 22 गज़ लंबी होती है — लगभग 20 मीटर, यानी 12 बच्चे लेट जाएँ इतनी!'},
  quiz:{en:'About how long is a cricket pitch?',hi:'क्रिकेट की पिच कितनी लंबी होती है?',opts:['20 metres','2 metres'],hiOpts:['20 मीटर','2 मीटर'],correct:0}},
 {id:'football',en:'Football',hi:'फ़ुटबॉल',ic:'⚽',type:'launch',actor:'🦵',proj:'⚽',accent:'#4C7BE0',
  fact:{en:'A football is stitched from 32 patches: 20 hexagons with 6 sides, and 12 pentagons with 5.',hi:'फ़ुटबॉल 32 टुकड़ों से सिली जाती है: 20 षट्भुज (6 भुजा) और 12 पंचभुज (5 भुजा)।'},
  quiz:{en:'How many sides does a hexagon have?',hi:'षट्भुज में कितनी भुजाएँ होती हैं?',opts:['6','5'],hiOpts:['6','5'],correct:0}},
 {id:'tennis',en:'Tennis',hi:'टेनिस',ic:'🎾',type:'launch',actor:'🎾',proj:'🎾',accent:'#F0A02A',
  fact:{en:'A tennis ball is fuzzy on purpose. The tiny hairs drag against the air and slow the ball down.',hi:'टेनिस गेंद पर रोएँ जान-बूझकर होते हैं। ये हवा से रगड़ खाकर गेंद को धीमा करते हैं।'},
  quiz:{en:'Why is a tennis ball fuzzy?',hi:'टेनिस गेंद रोएँदार क्यों होती है?',opts:['To slow it down','To make it heavy'],hiOpts:['धीमा करने के लिए','भारी बनाने के लिए'],correct:0}},
 {id:'basketball',en:'Basketball',hi:'बास्केटबॉल',ic:'🏀',type:'launch',actor:'🙌',proj:'🏀',accent:'#C5603A',
  fact:{en:'A basketball hoop is 3 metres high — that is two grown-ups standing on each other!',hi:'बास्केटबॉल का घेरा 3 मीटर ऊँचा होता है — दो बड़े लोग एक के ऊपर एक खड़े हों, इतना!'},
  quiz:{en:'How high is the hoop?',hi:'घेरा कितना ऊँचा होता है?',opts:['3 metres','30 metres'],hiOpts:['3 मीटर','30 मीटर'],correct:0}},
 {id:'badminton',en:'Badminton',hi:'बैडमिंटन',ic:'🏸',type:'launch',actor:'🏸',proj:'🏸',accent:'#E8447C',
  fact:{en:'A shuttlecock has exactly 16 feathers. Count them: 4 + 4 + 4 + 4 = 16.',hi:'शटल में ठीक 16 पंख होते हैं। गिनो: 4 + 4 + 4 + 4 = 16।'},
  quiz:{en:'How many feathers on a shuttlecock?',hi:'शटल में कितने पंख होते हैं?',opts:['16','6'],hiOpts:['16','6'],correct:0}},
 {id:'volleyball',en:'Volleyball',hi:'वॉलीबॉल',ic:'🏐',type:'launch',actor:'🙌',proj:'🏐',accent:'#4C7BE0',
  fact:{en:'Volleyball has 6 players on each side. 6 + 6 = 12 players on the whole court.',hi:'वॉलीबॉल में हर तरफ़ 6 खिलाड़ी होते हैं। 6 + 6 = 12 खिलाड़ी पूरे कोर्ट पर।'},
  quiz:{en:'How many players in total?',hi:'कुल कितने खिलाड़ी?',opts:['12','10'],hiOpts:['12','10'],correct:0}},
 {id:'squash',en:'Squash',hi:'स्क्वैश',ic:'🎾',type:'launch',actor:'🎾',proj:'⚫',accent:'#3FBB78',
  fact:{en:'A squash ball bounces higher when it is warm. Players hit it a few times first to heat it up!',hi:'स्क्वैश की गेंद गरम होने पर ज़्यादा उछलती है। खिलाड़ी पहले उसे मारकर गरम करते हैं!'},
  quiz:{en:'When does a squash ball bounce more?',hi:'स्क्वैश गेंद कब ज़्यादा उछलती है?',opts:['When warm','When cold'],hiOpts:['गरम होने पर','ठंडी होने पर'],correct:0}},
 {id:'pithoo',en:'Pithoo',hi:'पिट्ठू',ic:'🪨',type:'launch',actor:'🙋',proj:'🪨',accent:'#C5603A',
  fact:{en:'Pithoo uses 7 flat stones. The widest goes at the bottom — that is why the tower stands up.',hi:'पिट्ठू में 7 चपटे पत्थर होते हैं। सबसे चौड़ा नीचे रखते हैं — तभी ढेर खड़ा रहता है।'},
  quiz:{en:'Which stone goes at the bottom?',hi:'सबसे नीचे कौन सा पत्थर?',opts:['The widest','The smallest'],hiOpts:['सबसे चौड़ा','सबसे छोटा'],correct:0}},
 {id:'gilli',en:'Gilli Danda',hi:'गिल्ली डंडा',ic:'🪵',type:'launch',actor:'🪵',proj:'🥢',accent:'#F0A02A',
  fact:{en:'You tap one end of the gilli and the other end flies up. That is a lever — like a see-saw!',hi:'गिल्ली के एक सिरे पर मारो तो दूसरा उछल जाता है। यही लीवर है — सी-सॉ की तरह!'},
  quiz:{en:'Gilli danda works like a…',hi:'गिल्ली डंडा किसकी तरह काम करता है?',opts:['See-saw','Wheel'],hiOpts:['सी-सॉ','पहिया'],correct:0}},
 {id:'lattu',en:'Lattu',hi:'लट्टू',ic:'🌀',type:'launch',actor:'🪢',proj:'🌀',accent:'#E8447C',
  fact:{en:'A spinning top stays standing while it spins. The moment it slows down, it falls over.',hi:'लट्टू घूमते-घूमते खड़ा रहता है। जैसे ही धीमा होता है, गिर जाता है।'},
  quiz:{en:'Why does a lattu fall?',hi:'लट्टू क्यों गिरता है?',opts:['It slows down','It gets heavy'],hiOpts:['धीमा हो जाता है','भारी हो जाता है'],correct:0}},
 {id:'kanche',en:'Kanche',hi:'कंचे',ic:'🔵',type:'launch',actor:'👉',proj:'🔵',accent:'#4C7BE0',
  fact:{en:'When your marble hits another, it stops and the other shoots off. The push travels between them.',hi:'तुम्हारा कंचा दूसरे से टकराए तो वो रुक जाता है और दूसरा भाग जाता है। धक्का एक से दूसरे में चला जाता है।'},
  quiz:{en:'What passes from one marble to the other?',hi:'एक कंचे से दूसरे में क्या जाता है?',opts:['The push','The colour'],hiOpts:['धक्का','रंग'],correct:0}},
 {id:'pakdam',en:'Pakdam Pakdai',hi:'पकड़म पकड़ाई',ic:'🏃',type:'chase',actor:'🏃',actor2:'🏃‍♀️',accent:'#F0A02A',
  fact:{en:'The runner who covers more ground in the same time is faster. Speed is distance in a given time.',hi:'जो उतने ही समय में ज़्यादा दूरी तय करे वो तेज़ है। चाल यानी समय में तय की गई दूरी।'},
  quiz:{en:'Who is faster?',hi:'कौन तेज़ है?',opts:['More distance, same time','Less distance, same time'],hiOpts:['ज़्यादा दूरी, उतना समय','कम दूरी, उतना समय'],correct:0}},
 {id:'khokho',en:'Kho Kho',hi:'खो खो',ic:'🤸',type:'chase',actor:'🤸',actor2:'🏃',accent:'#3FBB78',
  fact:{en:'In kho kho, 8 players sit in a line facing opposite ways — left, right, left, right. A pattern!',hi:'खो खो में 8 खिलाड़ी बारी-बारी उल्टी दिशा में बैठते हैं — बाएँ, दाएँ, बाएँ, दाएँ। यही पैटर्न है!'},
  quiz:{en:'How do the sitting players face?',hi:'बैठे खिलाड़ी किस तरफ़ देखते हैं?',opts:['Alternate ways','All the same way'],hiOpts:['बारी-बारी उल्टा','सब एक तरफ़'],correct:0}},
 {id:'kabaddi',en:'Kabaddi',hi:'कबड्डी',ic:'🤼',type:'chase',actor:'🤼',actor2:'🏃',accent:'#C5603A',
  fact:{en:'A raider must say "kabaddi" without breathing in. Your lungs hold the air the whole time!',hi:'रेडर को बिना साँस लिए "कबड्डी" बोलना होता है। पूरी हवा तुम्हारे फेफड़ों में रुकी रहती है!'},
  quiz:{en:'What is the raider holding?',hi:'रेडर क्या रोके रखता है?',opts:['Their breath','Their hand'],hiOpts:['अपनी साँस','अपना हाथ'],correct:0}},
 {id:'chorsipahi',en:'Chor Sipahi',hi:'चोर सिपाही',ic:'👮',type:'chase',actor:'👮',actor2:'🏃',accent:'#4C7BE0',
  fact:{en:'Four folded chits, one says chor. Your chance of picking it is 1 out of 4 — one quarter.',hi:'चार मुड़ी पर्चियाँ, एक पर चोर। उसे उठाने का मौका 4 में से 1 है — यानी एक चौथाई।'},
  quiz:{en:'With 4 chits, your chance of chor is…',hi:'4 पर्चियों में चोर मिलने का मौका…',opts:['1 out of 4','1 out of 2'],hiOpts:['4 में से 1','2 में से 1'],correct:0}},
 {id:'langdi',en:'Langdi Taang',hi:'लंगड़ी टाँग',ic:'🦵',type:'chase',actor:'🦵',actor2:'🏃',accent:'#E8447C',
  fact:{en:'On one leg you wobble, so you spread your arms. Wide arms make it easier to balance.',hi:'एक टाँग पर डगमगाते हो, तो हाथ फैला लेते हो। फैले हाथ संतुलन आसान कर देते हैं।'},
  quiz:{en:'Why spread your arms?',hi:'हाथ क्यों फैलाते हैं?',opts:['To balance','To run faster'],hiOpts:['संतुलन के लिए','तेज़ दौड़ने के लिए'],correct:0}},
 {id:'chupan',en:'Chupan Chupai',hi:'छुपन छुपाई',ic:'🙈',type:'reveal',actor:'🙈',hide:'🌳',accent:'#3FBB78',
  fact:{en:'You count to 10 with eyes shut. Ten fingers, ten counts — that is why we count in tens!',hi:'आँखें बंद करके 10 तक गिनते हो। दस उँगलियाँ, दस गिनती — इसीलिए हम दस में गिनते हैं!'},
  quiz:{en:'Why do we count in tens?',hi:'हम दस में क्यों गिनते हैं?',opts:['Ten fingers','Ten letters'],hiOpts:['दस उँगलियाँ','दस अक्षर'],correct:0}},
 {id:'baraf',en:'Baraf Paani',hi:'बरफ़ पानी',ic:'🧊',type:'reveal',actor:'🧊',hide:'💧',accent:'#4C7BE0',
  fact:{en:'Real water turns to ice at 0 degrees, and melts back to water when it warms up. Baraf… paani!',hi:'असली पानी 0 डिग्री पर बरफ़ बन जाता है, और गरम होते ही फिर पानी। बरफ़… पानी!'},
  quiz:{en:'At what temperature does water freeze?',hi:'पानी किस तापमान पर जमता है?',opts:['0 degrees','100 degrees'],hiOpts:['0 डिग्री','100 डिग्री'],correct:0}},
 {id:'swimming',en:'Swimming',hi:'तैराकी',ic:'🏊',type:'reveal',actor:'🏊',hide:'🌊',accent:'#4C7BE0',
  fact:{en:'Fill your lungs with air and you float. Push all the air out and you sink. Try it!',hi:'फेफड़ों में हवा भर लो तो तैरते हो। सारी हवा निकाल दो तो डूबने लगते हो। आज़माओ!'},
  quiz:{en:'What helps you float?',hi:'तैरने में क्या मदद करता है?',opts:['Air in your lungs','Heavy arms'],hiOpts:['फेफड़ों की हवा','भारी हाथ'],correct:0}},
 {id:'stapu',en:'Stapu',hi:'स्टापू',ic:'🔢',type:'reveal',actor:'🦶',hide:'⬜',accent:'#F0A02A',
  fact:{en:'Stapu boxes are numbered 1 to 9. Hop them forward, then hop them backward — 9, 8, 7…',hi:'स्टापू के खाने 1 से 9 तक होते हैं। आगे कूदो, फिर उल्टा कूदो — 9, 8, 7…'},
  quiz:{en:'What comes before 8 when hopping back?',hi:'उल्टा कूदते हुए 8 से पहले क्या आता है?',opts:['9','7'],hiOpts:['9','7'],correct:0}}
];
const gameById = id => GAMES.find(g=>g.id===id) || GAMES[0];

const GREETS = {
  en:[n=>`Hey ${n}! What's up?`, n=>`${n}! You came back!`, n=>`Good to see you, ${n}!`, n=>`Ready, ${n}?`],
  hi:[n=>`अरे ${n}! क्या हाल है?`, n=>`${n}! तुम आ गए!`, n=>`तुम्हें देखकर अच्छा लगा, ${n}!`, n=>`तैयार हो, ${n}?`]
};
